repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-case-conflict
    -   id: check-toml
    -   id: fix-byte-order-marker
    -   id: mixed-line-ending
-   repo: https://github.com/pycqa/isort
    rev: '5.9.3'
    hooks:
    -   id: isort
-   repo: https://github.com/pycqa/flake8
    rev: '3.9.2'
    hooks:
    -   id: flake8
-   repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.7.2.1
    hooks:
    -   id: shellcheck
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.950
    hooks:
    -   id: mypy
        additional_dependencies: [types-setuptools]
