#!/bin/sh

# Put this file in .git/hooks

echo "Checking project..."

# Git hooks execute from the root of the repo
./scripts/check.sh
exit_status=$?

if [[ "${exit_status}" -ne 0 ]]; then
    printf "\033[31mERROR:\033[m pre-commit check returned ${exit_status}\n"
    exit ${exit_status}
fi
